# Generated by Django 5.0.7 on 2024-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs"),
        ),
    ]
